stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'MAEwNorm'
    encoder_config_path: 'facebook/vit-mae-base'
    encoder_input_size: 256
    encoder_params: {'model_name': 'facebook/vit-mae-base'}
    decoder_config_path: 'configs/decoder/ViTXL'
    pretrained_decoder_path: 'models/decoders/mae/base_p16/ViTXL_n08/model.pt'
    noise_tau: 0.
    reshape_to_2d: True
    normalization_stat_path: 'models/stats/mae/base_p16/ImageNet1k/stat.pt'